### ISSUE TITLE
explain how to use with id

### ISSUE THREAD

**Issue by nlehuby** [radiant-maxar/maprules#45]
The [latest id release](https://github.com/openstreetmap/iD/blob/master/CHANGELOG.md#2131) have support for Maprules. Can you add some doc or blog post to explain how to use it ?

**Comment by abalosc1** [comment]
After you've created a maprule, click the "Edit in iD" button and it should launch you to iD with the presets and validation rules loaded (it passes the link to them in the URL parameters)
https://medium.com/radiant-solutions/maprules-custom-tagging-presets-and-validation-rules-for-openstreetmap-581f8fa6df3d

**Comment by nlehuby** [comment]
In Maprule UI I assume ?

**Comment by abalosc1** [comment]
Yes. What that does is add the url where the validations and presets are posted to the iD parameters under `maprules` and `presets` respectively

**Comment by nlehuby** [comment]
Ok, sounds great!
I hope you will find some time to work on #42 (or maybe host a public version of the UI for the OSM communities) because I haven't manage yet to install the UI :crying_cat_face:
